config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :todo_lists do
    member do
      patch :complete
    end

    member do
      patch :incomplete
    end

  # To do items are nested under the todo_list
  # we do this because the todo_items belongs to a list. There should be a todo list first, before there can be a todo item. 
    resources :todo_items do
      member do
        patch :complete
      end
    end
    resources :todo_items do
      member do
          patch :incomplete
      end
  end 
  end

  root "todo_lists#index"
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo_item.rb
class TodoItem < ApplicationRecord
  belongs_to :todo_list

  def completed?
    !completed_at.blank?
  end

  def incomplete?
    completed_at.blank?
  end
end

app/models/todo_list.rb
class TodoList < ApplicationRecord
    has_many :todo_items, :dependent => :delete_all
    belongs_to :user
    def completed?
        !completed_at.blank?
      end
    
      def incomplete?
        completed_at.blank?
      end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :todo_lists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_todo_list
    before_action :set_todo_item, except: [:create]

    def create
        @todo_item = @todo_list.todo_items.new(todo_items_params)
    respond_to do |format|  
        if @todo_item.save
            format.html { redirect_to @todo_list}
            #  notice: 'Todo list was successfully created.' }
            format.json { render :show, status: :created, location: @todo_list }
        else
            format.html { redirect_to @todo_list, notice: 'Could not save' }
            format.json { render :show, status: :created, location: @todo_list }
        end
    end
    end

    # def create
    #     @todo_item = @todo_list.todo_items.create(todo_items_params)
    #     redirect_to @todo_list
    # end

    def edit
        @todo_item = @todo_list.todo_items.find(params[:id])
        # puts @todo_item
    end

    def update
        respond_to do |format|  
            if @todo_item.update(todo_items_params)
                format.html { redirect_to @todo_list} 
            else
                format.html { render :edit , notice: "could not update"}
                
            end
        end
    end
    
    def destroy
        # @todo_item = @todo_list.todo_items.find(params[:id])
        if @todo_item.destroy
         flash[:success] = "Todo List item was deleted."
        else
         flash[:error] = "Todo List item could not be deleted."
        end
        redirect_to @todo_list
    end

    def complete
        @todo_item.update_attribute(:completed_at,Time.now)
        redirect_to @todo_list
    end

    def incomplete
        @todo_item.update_attribute(:completed_at, nil)
        redirect_to @todo_list
    end
    private 
    def set_todo_list
        @todo_list = TodoList.find(params[:todo_list_id])
        # puts ">>>>>>" @todo_list
    end

    def set_todo_item
        @todo_item = @todo_list.todo_items.find(params[:id])
    end

    def todo_items_params 
        params[:todo_item].permit(:content)
    end


end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_todo_list, only: [:show, :edit, :update, :destroy, :complete, :incomplete]

  # GET /todo_lists
  # GET /todo_lists.json
  def index
    @todo_lists = TodoList.all.order('completed_at DESC')
    @todo_items = TodoItem.all
   
    # @todo_item = @todo_list.todo_items.all
    # puts ">>>>>>> #{@todo_lists.class}"
  end

  # GET /todo_lists/1
  # GET /todo_lists/1.json
  def show
    @todo_lists = TodoList.all
    @todo_items = TodoItem.all.order('completed_at DESC')
  end

  # GET /todo_lists/new
  def new
    @todo_list = current_user.todo_lists.build
  end

  # GET /todo_lists/1/edit
  def edit
    
  end

  # POST /todo_lists
  # POST /todo_lists.json
  def create
    @todo_list = current_user.todo_lists.build(todo_list_params)

    respond_to do |format|
      if @todo_list.save
        format.html { redirect_to root_path }
        format.json { render :show, status: :created, location: @todo_list }
      else
        format.html { render :new }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      
      end
    end
  end

  # PATCH/PUT /todo_lists/1
  # PATCH/PUT /todo_lists/1.json
  def update
    respond_to do |format|
      if @todo_list.update(todo_list_params)
        format.html { redirect_to root_path}
        format.json { render :show, status: :ok, location: @todo_list }
      else
        format.html { render :edit }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_lists/1
  # DELETE /todo_lists/1.json
  def destroy
    # @todo_item = @todo_list.todo_items.all
    # puts ">>>>>#{@todo_item}>>>>"
    @todo_list.destroy
    # check if the list is empty or not  
    respond_to do |format|
      format.html { redirect_to todo_lists_url}
      format.json { head :no_content }
    end
  end

  def complete
   
    @todo_list.update_attribute(:completed_at,Time.now)
    redirect_to root_path
  end

def incomplete
    @todo_list.update_attribute(:completed_at,nil)
    redirect_to root_path
end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_list
      @todo_list = TodoList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_list_params
      params.require(:todo_list).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <header class="row">
 
  <nav class="navbar col-sm-12"> 
    <% if user_signed_in? %>
       <nav class="navbar col-sm-6">
  <%# <%= link_to 'javascript:history.back()' do %>
    <%=link_to root_path do %>
    <i class="fa fa-home back"></i>
    <% end %>
  </nav>
      <ul class = "navbar ml-auto ">
        <%# <li class="nav-item"> <%= link_to 'Edit User-Info', edit_user_registration_path , class:"nav-link"%>     
        <li class="nav-item"> 
          <%= link_to destroy_user_session_path, method: :delete do %>   
            <i class="fa fa-sign-out logout"></i>
          <% end %>
        </li>
      </ul>      
    <% else %>
      <%= link_to 'Sign In', new_user_session_path %>  
    <% end %>  
  </nav>
  </header>

  <body>
  <!-- > <p class="notice"><%= notice %></p>
   <p class="alert"><%= alert %></p> -->
    <%= yield %>
  </body>
</html>

app/views/todo_items/_form.html.erb
  <%= form_for([@todo_list,@todo_list.todo_items.build])  do |f| %>
        <%= f.text_field :content, placeholder: "Add a Todo Item " , autofocus: "on", class:"form-control todo_item", required: true%></br>
        <%= f.submit "Submit", class:"btn btn-primary"%>
        <%# <%= link_to "Back" , root_path , :class => "btn btn-danger", method: :get %> 
    <% end %>

app/views/todo_items/_todo_item.html.erb
<% if todo_item.completed?%>
    <div class="completed">
        <p><strike> <%= todo_item.content %></strike></p>
        <%= link_to 'Edit', edit_todo_list_todo_item_path(@todo_list,todo_item.id) %>
        <%= link_to "Delete" , todo_list_todo_item_path(@todo_list, todo_item.id), method: :delete, data: { confirm: "Are you sure?" } %>
        <%= link_to "Complete", complete_todo_list_todo_item_path(@todo_list, todo_item.id), method: :patch %>
    </div>
<% else %>
        <p> <%= todo_item.content %></p>
        <%= link_to 'Edit', edit_todo_list_todo_item_path(@todo_list,todo_item.id) %>
        <%= link_to "Delete" , todo_list_todo_item_path(@todo_list, todo_item.id), method: :delete, data: { confirm: "Are you sure?" } %>
        <%= link_to "Complete", complete_todo_list_todo_item_path(@todo_list, todo_item.id), method: :patch %>
<% end %>

app/views/todo_items/_updateform.html.erb
<%= form_for ([@todo_list, @todo_list.todo_items.find(params[:id])])  do |f| %>
    <%= f.text_field :content, placeholder: "Add a Todo Item and hit enter" , class:"form-control todo_item", required: true%></br>
        <%= f.submit "Submit", class:"btn btn-primary"%>
<% end %>

app/views/todo_items/edit.html.erb
</br>
<center><h1> Edit Todo Items </h1>

<%= render "todo_items/updateform", todo_item: @todo_item %>
</center>

app/views/todo_lists/_form.html.erb
<%= form_with model: @todo_list do |form| %>
  <% if todo_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(todo_list.errors.count, "error") %> prohibited this todo_list from being saved:</h2>

      <ul>
      <% todo_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 
<div class="col-sm-8 offset-sm-2">
  <div class="fields form-group">
    <div class="field">
   <h1><%= form.label :title, "What do you have to do?" %></h1>
    <%= form.text_field :title, id: :todo_list_title, :class => 'form-control', placeholder: "start here",required: true %>
  </div>
  </br>
  <!--
  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :todo_list_description, :class => 'form-control', rows: "17",  placeholder: "Description", required: true  %>
  </div>
  </br> -->
  <div class="actions">
    <center><%= form.submit "Submit" ,:class => 'btn btn-success'%></center>
  <div>

</div>
<% end %>

app/views/todo_lists/edit.html.erb
<center><h1>Edit Todo List</h1></center>

<%= render 'form', todo_list: @todo_list %>

<%# <%= link_to 'Show', @todo_list %> 
<%# <%= link_to 'Back', todo_lists_path %> 

app/views/todo_lists/index.html.erb
<div class="container">
</br></br>
  
</br>
  <% if @todo_lists.length < 1 %>
      <h1> <center>The List is empty</center></h1>
  <% end %>
  <% @todo_lists.each do |todo_list| %>
    <% if todo_list.user == current_user %>  
      <div class="list_item">       
        <% if todo_list.completed?%>
            <div class="row">
              <div class="col-sm-8">
                <strike class="complete"><p class="list_title"> <%= todo_list.title[0,15].capitalize + "..."%></p></strike></div>
              <div class="col-sm-4">
              
                <%= link_to incomplete_todo_list_path(todo_list.id),method: :patch do%>
                  <i class="fa fa-square item-icons uncheck" ></i>
                <% end %>       
                <%= link_to todo_list, method: :delete, data: { confirm: 'Are you sure?' } do %>
                  <i class="fa fa-trash item-icons trash"></i>
              </div>
            </div>
                <% end %>  
        <% else %>
            <div class="row">
              <div class="col-sm-8">
             
                <% if todo_list.title.length > 15 %>
                  <p class="list_title"><%= link_to todo_list.title[0,15].capitalize + "...", todo_list %></p>
                <% else %>
                   <p class="list_title"><%= link_to todo_list.title.capitalize, todo_list %></p>
                <% end %>
              </div>
              <div class="col-sm-4">
               <%= link_to edit_todo_list_path(todo_list) do%>
                  <i class="fa fa-pencil item-icons pencil" ></i>
                <% end %> 
                <%= link_to complete_todo_list_path(todo_list.id),method: :patch do%>
                  <i class="fa fa-square-o item-icons check" ></i>
                <% end %>
                <%= link_to todo_list, method: :delete, data: { confirm: 'Are you sure?' } do %>
                  <i class="fa fa-trash item-icons trash"></i>
              </div>
            </div>                
            <% end %>
        <% end %>
      </div>
     
    <% end %>
  <% end %>
  <div class= "title">
    <%=link_to  new_todo_list_path, method: :get  do %> 
      <i class="fa fa-plus-circle add_item"></i>
    <% end %>
  </div>

  <%# <button onclick="myFunction()">Try it</button> %>
<!--
  </br>

   <div class="responsive table_container">  
  <table class="table">
        <thead class="thead-dark">
          <tr>
            <th width="200px">Title</th>
            <th width="600px">Description</th>
            <th colspan="4"></th>
          </tr>
        </thead> 
  <% @todo_lists.each do |todo_list| %>
    <% if todo_list.user == current_user %>     
        <tbody>
          <tr class="list_row">
          <% if todo_list.completed?%>
              <td><strike class="complete"> <%= todo_list.title.capitalize%></strike> </td>
              <td colspan =2 ></td>
               <td><%= link_to incomplete_todo_list_path(todo_list.id),method: :patch do%>
            <i class="fa fa-check-circle item-icons" ></i>
                  <% end %>               
            </td>    
            <td class="list_col"><%= link_to todo_list, method: :delete, data: { confirm: 'Are you sure?' } do %>
            <i class="fa fa-trash"></i>
            <% end %>
            </td>  
          <% else %>
            <td><%= link_to todo_list.title.capitalize, todo_list %></td>
            <td><%=link_to simple_format(todo_list.description), todo_list %>
            <%= button_to "Add Item", todo_list, class:"btn btn-primary", method: 'get' %>
            </td>  
            <td>
            <%= link_to complete_todo_list_path(todo_list.id),method: :patch do%>
            <i class="fa fa-check-circle item-icons" ></i>
                  <% end %>
            </td>
            <td class="list_col"><%= link_to edit_todo_list_path(todo_list) do %>
            <i class="fa fa-pencil"></i>
            <% end %>
            </td>
            <td class="list_col"><%= link_to todo_list, method: :delete, data: { confirm: 'Are you sure?' } do %>
            <i class="fa fa-trash"></i>
            <% end %>
            </td>
          <% end %>
          </tr>  
     
        <% @todo_items.each do |item|%>
          <% if todo_list.id == item.todo_list_id%>
            <tr class = "table-borderless table-sm ">
              <td colspan="1" style= "background :#ffffff"></td>
                <% if item.completed?%>
                  <td><strike class="complete"> <%= item.content.capitalize%></strike> </td>
                  <td  class="todo_items" >
                  <%= link_to incomplete_todo_list_todo_item_path(todo_list.id, item.id),method: :patch do%>
                  <i class="fa fa-check-circle item-icons" ></i>
                  <% end %>
                  </td>
                  <% else %>
                  <td> <%= item.content.capitalize%> </td>
                  <td  class="todo_items" >
                  <%= link_to complete_todo_list_todo_item_path(todo_list.id, item.id),method: :patch do%>
                  <i class="fa fa-check-circle item-icons" ></i>
                  <% end %>
                  </td>
                  <td class="todo_items" > 
                  <%= link_to edit_todo_list_todo_item_path(todo_list.id, item.id)  do %>
                  <i class="fa fa-pencil item-icons" ></i>
                  <% end %>
                  </td>                  
                  <td class="todo_items" >
                  <%= link_to todo_list_todo_item_path(todo_list.id, item.id), method: :delete, data: { confirm: "Are you sure?" } do%>
                  <i class="fa fa-trash item-icons"></i>
                  <% end %>
                  </td>                 
            </tr>
            </div>
            <% end %>
          <%end %>
        <% end %>
     <% end %>
    <% end %>
    </tbody>
  </table>
  </div>
</div>
<br>
 
</div> -->
 

app/views/todo_lists/new.html.erb
<%= render 'form', todo_list: @todo_list %>

app/views/todo_lists/show.html.erb
<!--<p id="notice"><%= notice %></p> -->
<table class="table table-striped">
<thead>
<p>
  <th><h1><strong>Todo:</strong>
  <%= @todo_list.title.capitalize %></br></h1>
  <%# <strong>Description:</strong> %>
  <%# <%= @todo_list.description %</br></br> --%>
  <%# <%= link_to 'Edit', edit_todo_list_path(@todo_list) %> 
  <%# <%= link_to 'Back', todo_lists_path %> 
</p></th>
</thead>
  <div style=" display:none"> <%= render @todo_list.todo_items %></div>


<table class="table responsive">
  <% @todo_items.each do |item|%>
    <% if @todo_list.id == item.todo_list_id%>
        <tr class = "table-borderless table-sm ">
          <td colspan="1" style= "background :#ffffff"></td>
              <% if item.completed?%>
                <td><strike class="complete"> <%= item.content.capitalize%></strike> </td>
                <td  class="todo_items" >
                <%= link_to incomplete_todo_list_todo_item_path(@todo_list.id, item.id),method: :patch do%>
                  <i class="fa fa-check-circle item-icons" ></i>
                <% end %>
                </td>
              <% else %>
                <td> <%= item.content.capitalize%> </td>
                <td  class="todo_items" >
                <%= link_to complete_todo_list_todo_item_path(@todo_list.id, item.id),method: :patch do%>
                  <i class="fa fa-check-circle item-icons" ></i>
                <% end %>
                </td>
                <td class="todo_items" >
                <%= link_to edit_todo_list_todo_item_path(@todo_list.id, item.id)  do %>
                  <i class="fa fa-pencil item-icons" ></i>
                <% end %>
                </td>             
                <td class="todo_items" >
                  <%= link_to todo_list_todo_item_path(@todo_list.id, item.id), method: :delete, data: { confirm: "Are you sure?" } do%>
                    <i class="fa fa-trash item-icons"></i>
                  <% end %>
                </td>                 
              <% end %>
        </tr>
    <% end %>              
  <%end%>
</table>
</br>
<center>
<div>
<%= render "todo_items/form" %>
</div>
</center>